coop_tilleuls_url_signer:
  signature_key: '%env(string:SIGNATURE_KEY)%' # The key is stored in project .env file
  default_expiration: 1 # One day
  expires_parameter: 'expired'
  signature_parameter: 'signature'