# Inquiries
inquiries:
    path: /poptavky
    controller: App\Controller\InquiryController::index
    methods: GET

inquiries/new:
    path: /poptavky/nova-poptavka
    controller: App\Controller\InquiryController::create
    methods: GET|POST

# Articles
home:
    path: /
    controller: App\Controller\HomeController::home
    methods: GET

inquiring:
    path: /poptavajici
    controller: App\Controller\HomeController::inquiring
    methods: GET

suppliers:
    path: /dodavatele
    controller: App\Controller\HomeController::supplier
    methods: GET

how-it-works:
    path: /jak-to-funguje
    controller: App\Controller\HomeController::howItWorks
    methods: GET

terms-and-conditions:
    path: /obchodni-podminky
    controller: App\Controller\HomeController::termsAndConditions
    methods: GET

# Auth
app_login:
    path: /prihlaseni
    controller: App\Controller\Auth\LoginController::login
    methods: GET|POST

app_register:
    path: /registrace
    controller: App\Controller\Auth\RegistrationController::register
    methods: GET|POST

app_verify_email:
    path: /overeni-emailu
    controller: App\Controller\Auth\RegistrationController::verifyUserEmail
    methods: GET

app_logout:
    path: /odhlasit
    controller: App\Controller\Auth\LogoutController::logout
    methods: GET