# Inquiries
inquiries:
  path: /poptavky
  controller: App\Controller\InquiryController::index
  methods: GET|POST

my-inquiries:
  path: /moje-poptavky
  controller: App\Controller\InquiryController::myInquiries
  methods: GET|POST

inquiries/new:
  path: /poptavky/nova-poptavka
  controller: App\Controller\InquiryController::create
  methods: GET|POST

inquiries/detail:
  path: /poptavka/{alias}
  controller: App\Controller\InquiryController::detail
  methods: GET|POST

inquiries/finish-signed:
  path: /dokoncit-poptavku
  controller: App\Controller\InquiryController::finishInquirySigned
  methods: GET|POST
  defaults:
    _signed: true # Deny access for unsigned

inquiries/finish:
  path: /moje-poptavky/{alias}/dokoncit-poptavku
  controller: App\Controller\InquiryController::finishInquiryAction
  methods: GET|POST

inquiries/supplier-rating:
  path: /hodnoceni-poptavajiciho
  controller: App\Controller\InquiryController::supplierRatingSigned
  methods: GET|POST
  defaults:
    _signed: true # Deny access for unsigned

inquiries/postpone-expiration:
  path: /prodlouzit-poptavku
  controller: App\Controller\InquiryController::postponeExpiration
  methods: GET|POST
  defaults:
    _signed: true # Deny access for unsigned

inquiries/attachments:
  path: /poptavky/prilohy/{hash}
  controller: App\Controller\InquiryAttachmentsController::download
  methods: GET

my-offers:
  path: /moje-nabidky
  controller: App\Controller\OfferController::listAction
  methods: GET

# Articles
home:
  path: /
  controller: App\Controller\HomeController::home
  methods: GET

inquiring:
  path: /poptavajici
  controller: App\Controller\HomeController::inquiring
  methods: GET

suppliers:
    path: /dodavatele
    controller: App\Controller\HomeController::supplier
    methods: GET

how-it-works:
    path: /jak-to-funguje
    controller: App\Controller\HomeController::howItWorks
    methods: GET

terms-and-conditions:
  path: /obchodni-podminky
  controller: App\Controller\HomeController::termsAndConditions
  methods: GET

# User
my-profile:
  path: /muj-ucet
  controller: App\Controller\AccountSettingsController::myProfile
  methods: GET

my-profile/base-settings:
  path: /muj-ucet/zakladni-nastaveni
  controller: App\Controller\AccountSettingsController::baseSettings
  methods: GET|POST

my-profile/change-password:
  path: /muj-ucet/zmena-hesla
  controller: App\Controller\AccountSettingsController::changePassword
  methods: GET|POST

my-profile/edit-profile:
  path: /muj-ucet/upravit-profil
  controller: App\Controller\AccountSettingsController::editMyProfile
  methods: GET|POST

my-profile/edit-inquiry-subscriptions:
  path: /muj-ucet/odber-poptavek
  controller: App\Controller\AccountSettingsController::editMySubscriptions
  methods: GET|POST

my-profile/edit-notifications:
  path: /muj-ucet/upozornovani
  controller: App\Controller\AccountSettingsController::editMyNotifications
  methods: GET|POST

# Profiles
profiles/detail:
  path: /profil/{profileId}
  controller: App\Controller\ProfileController::detail
  methods: GET

# Auth
app_login:
  path: /prihlaseni
  controller: App\Controller\Auth\LoginController::login
  methods: GET|POST

app_register:
  path: /registrace
  controller: App\Controller\Auth\RegistrationController::index
  methods: GET|POST

app_register_person:
    path: /registrace/soukromnik
    controller: App\Controller\Auth\RegistrationController::registerPerson
    methods: GET|POST

app_register_company:
  path: /registrace/firma
  controller: App\Controller\Auth\RegistrationController::registerCompany
  methods: GET|POST

app_verify_email:
  path: /overeni-emailu
  controller: App\Controller\Auth\UserVerificationController::verifyUserEmail
  methods: GET

app_verify_form:
  path: /potize-s-overenim-emailu
  controller: App\Controller\Auth\UserVerificationController::resendVerification
  methods: GET|POST

app_logout:
  path: /odhlasit
  controller: App\Controller\Auth\LogoutController::logout
  methods: GET

# Password reset request form.
app_reset_password/request:
  path: /zapomenute-heslo
  controller: App\Controller\Auth\ResetPasswordController::request
  methods: GET|POST

# Password reset form.
app_reset_password/reset:
  path: /zapomenute-heslo/obnova-hesla/{token?}
  controller: App\Controller\Auth\ResetPasswordController::reset

# Password reset link send view.
app_reset_password/check:
  path: /zapomenute-heslo/odeslano
  controller: App\Controller\Auth\ResetPasswordController::checkEmail
  methods: GET

admin:
  path: /admin
  controller: App\Controller\Admin\MainDashboardController::index