# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.items_per_page: 2

  app.verification_resend_delay: 300 # Interval between verification email resending in seconds. (5 minutes)

  # Interval between sending a notification that the inquiry is to be removed. (31 days)
  app.inquiries.auto_remove_notification_delay: 2678400
  # Interval between remove_notification and removing the inquiry. (7 days)
  app.inquiries.auto_remove_delay: 604800
  # It is possible to fill up rating form even if the inquiry is archived. The link expires in (31 days)
  app.inquiries.rating_link_expiration: 2678400

  # We have to append port number because running in symfony command do not know that and router is generating bad urls
  # This problem is dev only, because in production we (usually) use default port 80
  #router.request_context.host: 'localhost:8000'
